### ISSUE TITLE
ConfigxSpeed requires restart

### ISSUE THREAD

**Issue by StaticSapphic** [MapperTV/blockrunner#2]
Hi

I'm not sure if this is a bug or an intended feature/limitation, but the speeds in the blockrunner-server.toml file cannot be adjusted during game time like the block list or enabling/disabling can, and instead require the game to be restarted. I've tried reloading resources and quitting to title and neither of them help.

It's not a super big issue but I felt like I should bring it up since the block list and enabling/disabling can be edited during game time so this could be a mistake. If this cannot be fixed, could you add a warning in the config file about this so people know to restart? Something like
```
#Speed bonus - Requires game to be reloaded to take effect
```

Thanks! (And thanks for fixing the problem last time so quickly!)

blockrunner-1.16.4-1.1.0.0
forge-35.1.13

**Comment by MapperTV** [comment]
I just have no idea how to make it apply real time. I've looked a bit and there is something that can detect changes in config but it seems inconsistent depending of the system used by the player... I'll give a deeper look but for now you need to restart to apply new values.

Edit: give a try and looks like it works, sometimes the changes are not detected like people already reported on Forge discord but it's not a big deal (just edit one value, save, edit again and save again is a possible workaround).

**Comment by MapperTV** [comment]
1.2.0.0 version is now released with config changes being directly applied in game. Tags are also supported (ex: "#minecraft:sand" will apply speed bonus on all sand blocks including modded ones if the mods correctly use tags).

Minimal value is now -0.1 instead of -1.0 as it was a typo (-0.1 already removes all movement). The game will automatically limite the min and max values in case of.

Be sure to keep the console opened when making changes to see eventual errors (like from typos) and see if the config changes were actually applied because sometime changes are not detected (this is an issue depending of operating system and file management).
